[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['main', 'develop', 'feat/add-algolia']
  disabled = false
  pathPrefix = "/blog"
  customDomain = "example.com"
  renderJavaScript = true
